# Site settings
title: Jonas Andersson | Blog
url: "http://palkess.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: jonas.andersson.web@gmail.com
author: Jonas Andersson
avatar: "//avatars2.githubusercontent.com/u/5136414"
profile: Webdev. student and Teacher Assistant at Blekinge Institute of Technology. From Öland, Sweden but currently living in Karlskrona.
twitter_username: TehPalkess
github_username:  Palkess

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
